Repository Team-WeQuiz/wequiz, pull requests merged in 2024-03, with the labels that each got.

#96 [BE] CORS 설정
  chatty-be/src/main/java/com/chatty/chatty/config/WebConfig.java
  chatty-be/src/main/java/com/chatty/chatty/config/filter/CorsFilter.java
Labels: 🌏 Deploy, ⚙ Setting

#98 임시 integration API
  model/app/app.py
  model/app/data/vectorizer.py
Labels: ✨ Feature

#104 [FE] 도커 파일 추가
  chatty-fe/Dockerfile
  chatty-fe/next.config.js
  chatty-fe/src/app/(auth)/page.tsx
  chatty-fe/src/app/(main)/page.tsx
Labels: 🌏 Deploy

#107 [BE] Docker 및 Swagger 설정
  chatty-be/Dockerfile
  chatty-be/build.gradle
  chatty-be/src/main/java/com/chatty/chatty/quizroom/config/RestClientConfig.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/ModelService.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
  chatty-be/src/main/resources/application.yml
  docker-compose.yml
Labels: 🌏 Deploy

#108 [BE] 소셜로그인 초기 세팅 및 카카오 로그인 구현
  chatty-be/build.gradle
  chatty-be/src/main/java/com/chatty/chatty/ChattyApplication.java
  chatty-be/src/main/java/com/chatty/chatty/auth/config/FeignConfiguration.java
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/oauth/OAuthController.java
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/oauth/dto/KakaoLoginResponse.java
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/oauth/dto/SocialAuthResponse.java
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/oauth/dto/SocialLoginRequest.java
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/oauth/dto/SocialUserResponse.java
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/oauth/kakao/KakaoAuthApi.java
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/oauth/kakao/KakaoUserApi.java
  chatty-be/src/main/java/com/chatty/chatty/auth/entity/Provider.java
  chatty-be/src/main/java/com/chatty/chatty/auth/exception/AuthExceptionType.java
  chatty-be/src/main/java/com/chatty/chatty/auth/jwt/JwtUtil.java
  chatty-be/src/main/java/com/chatty/chatty/auth/service/oauth/KakaoLoginService.java
  chatty-be/src/main/java/com/chatty/chatty/auth/service/oauth/OAuthService.java
  chatty-be/src/main/java/com/chatty/chatty/auth/service/oauth/SocialLoginService.java
  chatty-be/src/main/java/com/chatty/chatty/auth/support/GsonLocalDateTimeAdapter.java
  chatty-be/src/main/java/com/chatty/chatty/user/entity/User.java
  chatty-be/src/main/resources/application-local.yml
Labels: ✨ Feature

#112 [FE] docker compose 프론트 추가
  docker-compose.yml
Labels: 🌏 Deploy

#120 [BE] QuizRoom Entity에서 link 삭제
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/MakeRoomResponse.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/entity/QuizRoom.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
Labels: 🔨 Refactor

#121 [BE] 문제 생성 요청 관련 dto 수정
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/MakeRoomRequest.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
Labels: 🔨 Refactor

#122 [BE] refresh token 재발급 api
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/AuthController.java
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/dto/RefreshTokenRequest.java
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/dto/SignInResponse.java
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/dto/SignUpResponse.java
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/oauth/OAuthController.java
  chatty-be/src/main/java/com/chatty/chatty/auth/exception/AuthExceptionType.java
  chatty-be/src/main/java/com/chatty/chatty/auth/interceptor/LoginInterceptor.java
  chatty-be/src/main/java/com/chatty/chatty/auth/jwt/JwtUtil.java
  chatty-be/src/main/java/com/chatty/chatty/auth/repository/RefreshTokenRepository.java
  chatty-be/src/main/java/com/chatty/chatty/auth/service/AuthService.java
  chatty-be/src/main/java/com/chatty/chatty/auth/service/oauth/OAuthService.java
  chatty-be/src/main/resources/application-local.yml
Labels: ✨ Feature

#125 [BE] UserInfo 가져오는 api 구현
  chatty-be/src/main/java/com/chatty/chatty/auth/config/AuthConfig.java
  chatty-be/src/main/java/com/chatty/chatty/auth/exception/AuthExceptionType.java
  chatty-be/src/main/java/com/chatty/chatty/auth/service/AuthService.java
  chatty-be/src/main/java/com/chatty/chatty/user/controller/UserController.java
  chatty-be/src/main/java/com/chatty/chatty/user/controller/dto/UserInfoResponse.java
  chatty-be/src/main/java/com/chatty/chatty/user/entity/User.java
  chatty-be/src/main/java/com/chatty/chatty/user/exception/UserException.java
  chatty-be/src/main/java/com/chatty/chatty/user/exception/UserExceptionType.java
  chatty-be/src/main/java/com/chatty/chatty/user/service/UserService.java
Labels: ✨ Feature

#130 [BE] 로그인할 때 refreshToken도 제공하도록 수정
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/AuthController.java
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/dto/SignUpResponse.java
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/dto/TokenResponse.java
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/oauth/OAuthController.java
  chatty-be/src/main/java/com/chatty/chatty/auth/entity/RefreshToken.java
  chatty-be/src/main/java/com/chatty/chatty/auth/service/AuthService.java
  chatty-be/src/main/java/com/chatty/chatty/auth/service/oauth/OAuthService.java
Labels: ✨ Feature

#150 [BE] Entity not null 설정
  chatty-be/src/main/java/com/chatty/chatty/player/entity/Player.java
  chatty-be/src/main/java/com/chatty/chatty/user/entity/User.java
Labels: 🔨 Refactor

#151 [BE] Entity not null 설정
  chatty-be/src/main/java/com/chatty/chatty/player/entity/Player.java
  chatty-be/src/main/java/com/chatty/chatty/user/entity/User.java
Labels: 🔨 Refactor

#144 ML 서버 도커 테스트
  model/Dockerfile
  model/README.md
  model/app/model/chain.py
  model/app/model/embedding.py
Labels: ✨ Feature

#162 [BE] 소셜 로그인할 때 리프레쉬 토큰을 발급하지 않던 버그 수정
  chatty-be/src/main/java/com/chatty/chatty/auth/service/oauth/OAuthService.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/exception/QuizRoomException.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/exception/QuizRoomExceptionType.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/ModelService.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
Labels: 🐞 BugFix

#164 [FE] 로그인 여부에 따른 페이지 가드
  chatty-fe/next.config.js
  chatty-fe/package-lock.json
  chatty-fe/package.json
  chatty-fe/src/app/(auth)/sign-in/google/callback/page.tsx
  chatty-fe/src/app/(auth)/sign-in/kakao/callback/page.tsx
  chatty-fe/src/app/(auth)/sign-in/page.tsx
  chatty-fe/src/app/(auth)/sign-up/page.tsx
  chatty-fe/src/app/(game)/_components/AuthCheck.tsx
  chatty-fe/src/app/(game)/layout.tsx
  chatty-fe/src/app/_api/auth.ts
  chatty-fe/src/app/_lib/auth.ts
  chatty-fe/src/app/_store/useAuthStore.ts
  chatty-fe/src/middleware.ts
Labels: ✨ Feature, 🔨 Refactor

#180 문제 생성 API에 DynamoDB 연결
  model/Dockerfile
  model/README.md
  model/app/app.py
Labels: 📬 API, ✨ Feature
