Repository Team-WeQuiz/wequiz, pull requests merged in 2024-04, with the labels that each got.

#189 [BE] 퀴즈룸에 유저 입장할 수 있도록 구현
  chatty-be/src/main/java/com/chatty/chatty/auth/config/AuthConfig.java
  chatty-be/src/main/java/com/chatty/chatty/auth/jwt/JwtUtil.java
  chatty-be/src/main/java/com/chatty/chatty/auth/support/AuthenticationExtractor.java
  chatty-be/src/main/java/com/chatty/chatty/config/WebSocketConfig.java
  chatty-be/src/main/java/com/chatty/chatty/config/interceptor/StompHandler.java
  chatty-be/src/main/java/com/chatty/chatty/player/entity/Player.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/GameController.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/QuizRoomController.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/SocketController.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/ChatRequest.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/ChatResponse.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/PlayersStatusDTO.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/domain/PlayerStatus.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/domain/PlayersStatus.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/domain/entity/QuizRoom.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/domain/entity/Status.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/repository/PlayersStatusRepository.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/repository/QuizRoomRepository.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/GameService.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/SocketService.java
  chatty-be/src/main/resources/application-local.yml
  chatty-be/src/test/java/com/chatty/chatty/user/service/UserServiceTest.java
Labels: 📬 API, 🐞 BugFix, ✨ Feature

#193 [BE] 플레이어 준비 상태 변경 및 퇴장 api
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/GameController.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/domain/PlayerStatus.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/domain/PlayersStatus.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/repository/PlayersStatusRepository.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/GameService.java
  chatty-be/src/test/java/com/chatty/chatty/user/service/UserServiceTest.java
Labels: ✨ Feature

#202 [BE] stomp 에러 핸들링 및 채팅에서 user를 header를 통해 받도록 수정
  chatty-be/src/main/java/com/chatty/chatty/auth/jwt/JwtUtil.java
  chatty-be/src/main/java/com/chatty/chatty/config/WebSocketConfig.java
  chatty-be/src/main/java/com/chatty/chatty/config/interceptor/StompHandler.java
  chatty-be/src/main/java/com/chatty/chatty/exception/StompExceptionHandler.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/GameController.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/ChatRequest.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/repository/PlayersStatusRepository.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/GameService.java
Labels: ✨ Feature, 🔨 Refactor

#205 [BE] 데이터베이스를 mysql로 변경
  chatty-be/build.gradle
  chatty-be/src/main/resources/application-local.yml
Labels: ⚙ Setting

#206 [BE]Config: 백엔드 도커 파일 수정
  chatty-be/Dockerfile
Labels: 🌏 Deploy

#207 [feat/#204] :bug: Fix: db 설정 오타 수정
  chatty-be/src/main/resources/application-local.yml
Labels: 🐞 BugFix

#212 [test/cicd] Test: docker network 설정 하는 쪽으로 다시 복구
  chatty-be/src/main/resources/application-prod.yml
Labels: 🌏 Deploy

#210 [BE] AWS 설정
  chatty-be/build.gradle
  chatty-be/src/main/java/com/chatty/chatty/aws/config/AWSKey.java
  chatty-be/src/main/java/com/chatty/chatty/aws/config/DynamoDBConfig.java
  chatty-be/src/main/resources/application.yml
Labels: ⚙ Setting

#223 [ML] 문제 생성, 채점 API DTO 수정
  model/.gitignore
  model/app/app.py
  model/app/data/prob_generator.py
  model/app/schema.py
Labels: 📬 API

#228 data 파일 내 코드 리팩토링 및 병합
  model/.gitignore
  model/app/app.py
  model/app/data/generator.py
  model/app/data/loader.py
  model/app/data/marker.py
  model/app/data/parsers/__init__.py
  model/app/data/parsers/pdf.py
  model/app/data/preprocessor.py
  model/app/data/settings.py
  model/app/data/splitter.py
  model/app/data/summarizer.py
  model/app/data/vectorizer.py
Labels: 🔨 Refactor

#230 [ML] Docker에서 OCR 기능 터지는 문제 해결
  model/Dockerfile
Labels: 🐞 BugFix

#244 [ML] 요약 체인 비동기화
  model/app/app.py
  model/app/data/generator.py
  model/app/data/preprocessor.py
  model/app/model/chain.py
Labels: ⚡ Improve

#249 [ML] 텍스트 전처리, 요약 테스트
  model/app/app.py
  model/app/data/preprocessor.py
  model/app/data/settings.py
  model/app/model/chain.py
Labels: ⚡ Improve, 🧪 Experiment

#233 [BE] 요약과 문제 반환
  chatty-be/src/main/java/com/chatty/chatty/ChattyApplication.java
  chatty-be/src/main/java/com/chatty/chatty/config/DynamoDBConfig.java
  chatty-be/src/main/java/com/chatty/chatty/config/RestClientConfig.java
  chatty-be/src/main/java/com/chatty/chatty/config/WebSocketConfig.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/DescriptionResponse.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/QuizResponse.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/dynamodb/Quiz.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/QuizData.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/GameRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/dynamodb/DynamoDBRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/dynamodb/DynamoDBService.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/model/ModelService.java
  chatty-be/src/main/java/com/chatty/chatty/player/controller/dto/PlayersStatusDTO.java
Labels: 📬 API, ✨ Feature

#253 [ML] 파싱, 요약 시간 조정
  model/app/app.py
  model/app/data/preprocessor.py
  model/app/model/prompt.py
Labels: ⚡ Improve, 🧪 Experiment

#261 [BE] :sparkles: Feat: 방 생성 로직 분리하여 방 생성 요청 시 roomId 만 반환
  chatty-be/src/main/java/com/chatty/chatty/config/minio/MinioRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/model/CreateQuizRequest.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/model/ModelService.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/CreateRoomResponse.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/GenerateQuizMLResponse.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/QuizDocIdMLResponse.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
  chatty-be/src/test/java/com/chatty/chatty/model/service/ModelServiceTest.java
Labels: 📬 API

#264 [BE] minio에 저장하는 경로 변경
  chatty-be/src/main/java/com/chatty/chatty/common/util/Sha256Encrypt.java
  chatty-be/src/main/java/com/chatty/chatty/config/minio/MinioRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/model/ModelService.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/exception/FileExceptionType.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
Labels: 🔨 Refactor

#270 [BE] :bug: Fix: 퀴즈룸 상세정보 api 수정
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/QuizRoomController.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/CreateRoomRequest.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/RoomDetailResponse.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/RoomQuizResponse.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/entity/QuizRoom.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
Labels: 📬 API

#273 [ML] 문제 생성 방식 수정 (임시)
  model/README.md
  model/app/app.py
  model/app/data/generator.py
  model/app/model/chain.py
  model/app/model/prompt.py
Labels: ⚡ Improve

#276 [BE] 디스크립션 및 퀴즈를 폴링으로 전달
  chatty-be/src/main/java/com/chatty/chatty/auth/config/AuthConfig.java
  chatty-be/src/main/java/com/chatty/chatty/config/WebSocketConfig.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/QuizData.java
  chatty-be/src/main/java/com/chatty/chatty/game/exception/GameException.java
  chatty-be/src/main/java/com/chatty/chatty/game/exception/GameExceptionType.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/GameRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/dynamodb/DynamoDBService.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/QuizRoomController.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
  chatty-be/src/main/resources/application-local.yml
  chatty-be/src/main/resources/application-prod.yml
Labels: ✨ Feature, 🔨 Refactor, ⚙ Setting
