Repository Team-WeQuiz/wequiz, pull requests merged in 2024-05, with the labels that each got.

#293 [ML] 쿼리와 유사한 문서 검색하는 부분 수정
  model/app/data/settings.py
  model/app/model/chain.py
  model/app/model/prompt.py
Labels: ⚡ Improve, 🧪 Experiment

#295 [ML] 요약용, 벡터db용 문서 split 분리
  model/app/app.py
  model/app/data/preprocessor.py
  model/app/data/settings.py
  model/app/model/chain.py
Labels: ✨ Feature, 🧪 Experiment

#292 [BE] 방 입장할 때 닉네임 설정
  chatty-be/Dockerfile
  chatty-be/src/main/java/com/chatty/chatty/common/entity/BaseEntity.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
  chatty-be/src/main/java/com/chatty/chatty/player/controller/dto/NicknameRequest.java
  chatty-be/src/main/java/com/chatty/chatty/player/domain/PlayerStatus.java
  chatty-be/src/main/java/com/chatty/chatty/player/domain/PlayersStatus.java
  chatty-be/src/main/java/com/chatty/chatty/player/domain/entity/Player.java
  chatty-be/src/main/java/com/chatty/chatty/player/exception/PlayerException.java
  chatty-be/src/main/java/com/chatty/chatty/player/exception/PlayerExceptionType.java
  chatty-be/src/main/java/com/chatty/chatty/player/repository/PlayersStatusRepository.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/entity/QuizRoom.java
  chatty-be/src/main/java/com/chatty/chatty/user/entity/User.java
  docker-compose.yml
Labels: ✨ Feature

#302 [BE] 플레이어 제출 상태 및 게임 시작 api
  chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/SubmitAnswerRequest.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/SubmitAnswerResponse.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/dynamodb/Quiz.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/UserSubmitStatus.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/UsersSubmitStatus.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/AnswerRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/UserSubmitStatusRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
  chatty-be/src/main/java/com/chatty/chatty/player/repository/PlayersStatusRepository.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/QuizRoomController.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/entity/QuizRoom.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/exception/QuizRoomExceptionType.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/repository/QuizRoomRepository.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
Labels: ✨ Feature

#303 [BE] 점수 계산
  chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/ScoreResponse.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/SubmitAnswerRequest.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/dynamodb/Quiz.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/model/MarkRequest.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/model/MarkResponse.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/Answer.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/AnswerData.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/ScoreData.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/AnswerRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/ScoreRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/QuizDataService.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#309 [ML] 키워드 추출, 키워드 기반 문제 생성, 문제 생성 예외 처리 추가
  model/app/app.py
  model/app/data/keyword.py
  model/app/data/korean_stopwords.py
  model/app/data/preprocessor.py
  model/app/data/settings.py
Labels: ✨ Feature, ⚡ Improve, 🧪 Experiment

#315 [ML] 문제 생성 chain 리팩토링, 문제 생성 예외처리
  model/app/app.py
  model/app/data/generator.py
  model/app/data/loader.py
  model/app/data/preprocessor.py
  model/app/data/settings.py
  model/app/model/chain.py
  model/app/model/prompt.py
Labels: 🔨 Refactor

#318 [ML] 체인 단계 분리, 프롬프트 최적화
  model/Dockerfile
  model/app/data/generator.py
  model/app/data/settings.py
  model/app/experiments.py
  model/app/model/chain.py
  model/app/model/prompt.py
  model/app/model/schema.py
Labels: ⚡ Improve, 🧪 Experiment

#326 [ML] 언어에 따른 토크나이저 사용
  model/Dockerfile
  model/app/data/keyword.py
  model/mecab_install.sh
Labels: ⚡ Improve

#339 [BE] 소셜로그인 및 db 설정 aws secret manager 연동
  chatty-be/src/main/resources/application-local.yml
  chatty-be/src/main/resources/application-prod.yml
  chatty-be/src/main/resources/application.yml
Labels: 🌏 Deploy, ⚙ Setting

#351 [BE] 마이페이지 api 구현
  chatty-be/src/main/java/com/chatty/chatty/auth/config/AuthConfig.java
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/AuthController.java
  chatty-be/src/main/java/com/chatty/chatty/auth/controller/dto/PasswordRequest.java
  chatty-be/src/main/java/com/chatty/chatty/auth/service/AuthService.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
  chatty-be/src/main/java/com/chatty/chatty/player/repository/PlayerRepository.java
  chatty-be/src/main/java/com/chatty/chatty/player/service/PlayerService.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
  chatty-be/src/main/java/com/chatty/chatty/user/controller/UserController.java
  chatty-be/src/main/java/com/chatty/chatty/user/controller/dto/ParticipatedQuizRoomDTO.java
  chatty-be/src/main/java/com/chatty/chatty/user/controller/dto/ParticipatedQuizRoomListResponse.java
  chatty-be/src/main/java/com/chatty/chatty/user/entity/User.java
  chatty-be/src/main/java/com/chatty/chatty/user/service/UserService.java
  chatty-be/src/main/resources/application-prod.yml
Labels: ✨ Feature

#352 [BE] :sparkles: Feat: 요청하는 pdf의 토큰이 적을 경우 에러 반환
  chatty-be/src/main/java/com/chatty/chatty/config/minio/MinioRepository.java
  chatty-be/src/main/java/com/chatty/chatty/config/minio/exception/MinioExceptionType.java
  chatty-be/src/main/java/com/chatty/chatty/game/exception/ModelException.java
  chatty-be/src/main/java/com/chatty/chatty/game/exception/ModelExceptionType.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/model/ModelService.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
  chatty-be/src/main/java/com/chatty/chatty/user/controller/UserController.java
  chatty-be/src/main/java/com/chatty/chatty/user/service/UserService.java
Labels: ✨ Feature, ⚡ Improve

#355 [ML] 비동기처리
  model/app/app.py
  model/requirements.txt
Labels: 📬 API

#361 [ML] 동시 요청 문제
  model/Dockerfile
  model/app/app.py
  model/app/data/generator.py
  model/app/data/loader.py
  model/app/data/preprocessor.py
  model/requirements_compact.txt
Labels: 📬 API, ⚡ Improve

#363 [FE] 환경 변수 수정, 방 만들기 수정
  chatty-fe/.env.production
  chatty-fe/.gitignore
  chatty-fe/src/app/(auth)/sign-in/page.tsx
  chatty-fe/src/app/(game)/create-room/_components/FileUploadBox.css.ts
  chatty-fe/src/app/(game)/create-room/_components/FileUploadBox.tsx
  chatty-fe/src/app/(game)/create-room/_components/QuestionMaker/QuestionMaker.tsx
  chatty-fe/src/app/(game)/create-room/page.tsx
  chatty-fe/src/app/_api/auth.ts
  chatty-fe/src/app/_components/TextInputField.tsx
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css, ⚙ Setting, ⚡ Improve

#358 [BE] 결과 반환 API
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/ScoreResponse.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/SubmitAnswerRequest.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/dynamodb/MarkDTO.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/dynamodb/QuizDTO.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/QuizData.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/ScoreData.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/AnswerRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/GameRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/ScoreRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/dynamodb/DynamoDBRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/dynamodb/DynamoDBService.java
  chatty-be/src/main/java/com/chatty/chatty/player/domain/entity/Player.java
  chatty-be/src/main/java/com/chatty/chatty/player/exception/PlayerExceptionType.java
  chatty-be/src/main/java/com/chatty/chatty/player/repository/PlayerRepository.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/QuizRoomController.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/QuizResultDTO.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/RoomQuizResponse.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/RoomResultResponse.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/entity/QuizRoom.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
Labels: 📬 API

#374 [ML] 문제 생성 함수 비동기화
  model/Dockerfile
  model/app/app.py
  model/app/data/generator.py
  model/app/data/korean_stopwords.py
  model/app/data/settings.py
  model/app/model/chain.py
Labels: ⚡ Improve

#380 [BE] 플레이어 수 업뎃 되기 전에 답안큐 초기화 되는 문제 해결
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/QuizReadyResponse.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
Labels: 📬 API, 🔨 Refactor

#381 [BE] 프로필 사진 업로드 및 조회 기능
  chatty-be/src/main/java/com/chatty/chatty/auth/config/AuthConfig.java
  chatty-be/src/main/java/com/chatty/chatty/config/minio/MinioRepository.java
  chatty-be/src/main/java/com/chatty/chatty/config/minio/exception/MinioExceptionType.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
  chatty-be/src/main/java/com/chatty/chatty/user/controller/UserController.java
  chatty-be/src/main/java/com/chatty/chatty/user/controller/dto/ProfileImageRequest.java
  chatty-be/src/main/java/com/chatty/chatty/user/entity/User.java
  chatty-be/src/main/java/com/chatty/chatty/user/service/UserService.java
  chatty-be/src/main/resources/application-local.yml
  chatty-be/src/main/resources/application.yml
Labels: ✨ Feature

#386 [BE] 제출 상태 DTO 수정
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/SubmitAnswerResponse.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/AnswerData.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/SubmitStatus.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/AnswerRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
Labels: 🐞 BugFix, 🔨 Refactor

#390 [FE] 제출 상태 DTO 수정 반영, submit message 수정
  chatty-fe/src/app/(game)/mypage/_component/UserQuizList/UserQuizList.tsx
  chatty-fe/src/app/(game)/quiz-room/[id]/page.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#393 [BE] 퀴즈 삭제 후 다음 퀴즈 넘기게 수정
  chatty-be/src/main/java/com/chatty/chatty/game/domain/QuizData.java
  chatty-be/src/main/java/com/chatty/chatty/game/exception/GameExceptionType.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/AnswerRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
Labels: 🐞 BugFix

#396 [BE] :bug: Fix: 프로필 사진 변경 시 minio에서 기존 저장되어 있던 프로필 사진 삭제
  chatty-be/src/main/java/com/chatty/chatty/config/minio/MinioRepository.java
  chatty-be/src/main/java/com/chatty/chatty/user/service/UserService.java
Labels: 🐞 BugFix

#398 [BE] 6자리 코드로 방 접속 api
  chatty-be/src/main/java/com/chatty/chatty/common/util/RandomCodeGenerator.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/QuizRoomController.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/CodeRequestDTO.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/CreateRoomRequest.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/RoomDetailResponse.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/RoomIdResponse.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/entity/QuizRoom.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/exception/QuizRoomExceptionType.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/repository/QuizRoomRepository.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
Labels: ✨ Feature

#401 [BE] Phase를 넣어서 소켓 데이터 전달 단계 구분
  chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/AnswerData.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/Phase.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/PhaseRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/UserSubmitStatusRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
Labels: ✨ Feature

#406 [BE] user status가 필요한 곳에 프로필 이미지 추가
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/ScoreResponse.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/ScoreData.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/UserSubmitStatus.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/UsersSubmitStatus.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
  chatty-be/src/main/java/com/chatty/chatty/player/domain/PlayerStatus.java
  chatty-be/src/main/java/com/chatty/chatty/player/domain/PlayersStatus.java
  chatty-be/src/main/java/com/chatty/chatty/player/repository/PlayersStatusRepository.java
Labels: ✨ Feature

#409 [BE] Phase 저장이 필요한 곳에 추가 반영
  chatty-be/src/main/java/com/chatty/chatty/game/domain/QuizData.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
  chatty-be/src/main/java/com/chatty/chatty/player/repository/PlayersStatusRepository.java
  chatty-be/src/main/java/com/chatty/chatty/user/service/UserService.java
Labels: 🐞 BugFix, ✨ Feature

#413 [BE] 다음 퀴즈 요청 조건 수정
  chatty-be/src/main/java/com/chatty/chatty/game/domain/QuizData.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
  chatty-be/src/main/java/com/chatty/chatty/player/repository/PlayersStatusRepository.java
  chatty-be/src/main/java/com/chatty/chatty/user/service/UserService.java
Labels: 📬 API, 🐞 BugFix

#426 [BE] 룸 상세 정보에 인원 다 차있는지 여부 전달
  chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/RoomDetailResponse.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/entity/QuizRoom.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
Labels: 🐞 BugFix, ✨ Feature

#429 [BE] 제출 상태 갱신되는대로 전송
  chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
Labels: 📬 API, 🐞 BugFix

#433 [BE] 웹 소켓 Disconnect 되었을 때 이벤트리스너 구현
  chatty-be/src/main/java/com/chatty/chatty/config/WebSocketEventListener.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
Labels: ✨ Feature

#435 [BE] :bug: Fix: 커넥션이 끊어 질 때 방 상태에 따라 분기 설정
  chatty-be/src/main/java/com/chatty/chatty/config/WebSocketEventListener.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
  chatty-be/src/main/java/com/chatty/chatty/player/domain/PlayersStatus.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
Labels: 🐞 BugFix

#440 [ML] OX퀴즈 채점 오류 수정
  model/app/data/generator.py
  model/app/data/settings.py
Labels: 🐞 BugFix

#442 [BE] 중간 점수 한 명한테만 뜨는 버그 수정
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
Labels: 🐞 BugFix

#443 [BE] 웹 소켓 재연결할 때 레디상태가 초기화되던 버그 수정
  chatty-be/src/main/java/com/chatty/chatty/auth/support/AuthenticationContext.java
  chatty-be/src/main/java/com/chatty/chatty/config/GlobalMessagingTemplate.java
  chatty-be/src/main/java/com/chatty/chatty/config/WebSocketEventListener.java
  chatty-be/src/main/java/com/chatty/chatty/config/interceptor/StompHandler.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/QuizResultDTO.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
  chatty-be/src/main/java/com/chatty/chatty/user/service/UserService.java
Labels: 🐞 BugFix, 🔨 Refactor

#447 [feat/#446] :sparkles: feat: 100메가 초과 파일 업로드 시 얼럿
  chatty-fe/src/app/(game)/create-room/page.tsx
  chatty-fe/src/app/_api/createRoom.ts
Labels: ✨ Feature

#458 [BE] JwtUtil 클래스 테스트 작성
  chatty-be/src/main/java/com/chatty/chatty/auth/jwt/JwtUtil.java
  chatty-be/src/main/java/com/chatty/chatty/config/WebSocketEventListener.java
  chatty-be/src/test/java/com/chatty/chatty/auth/jwt/JwtUtilTest.java
  chatty-be/src/test/java/com/chatty/chatty/helper/MockBeanInjection.java
Labels: ✅ Test

#469 [ML] 채점, 퀴즈 디비 스키마, 필드명 수정
  model/app/app.py
  model/app/data/generator.py
  model/app/schema.py
Labels: 🔨 Refactor

#424 [feat/#311] :sparkles: Feat: 기존 문제 가져오는 api
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/SubmitAnswerResponse.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/dynamodb/MarkDTO.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/model/CreateQuizRequest.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/model/MarkRequest.java
  chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/model/MarkResponse.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/AnswerData.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/QuizData.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/AnswerRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/GameRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/dynamodb/DynamoDBRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/dynamodb/DynamoDBService.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/model/ModelService.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/QuizRoomController.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/CreateRoomRequest.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/ExistQuizListResponse.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/entity/QuizRoom.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
Labels: 📬 API, ✨ Feature

#463 [BE] Test: AuthController - 일반 회원가입하면 토큰을 반환한다
  chatty-be/build.gradle
  chatty-be/src/main/java/com/chatty/chatty/auth/service/AuthService.java
  chatty-be/src/main/java/com/chatty/chatty/auth/support/BCryptPasswordEncoder.java
  chatty-be/src/main/resources/application-prod.yml
  chatty-be/src/test/java/com/chatty/chatty/auth/controller/AuthControllerTest.java
Labels: 🔨 Refactor, ✅ Test

#480 [ML] 문장단위 TextSplitter 제작
  model/Dockerfile
  model/app/app.py
  model/app/data/generator.py
  model/app/data/korean_stopwords.py
  model/app/data/preprocessor.py
  model/app/data/settings.py
  model/app/model/chain.py
  model/app/model/prompt.py
Labels: ✨ Feature, ⚡ Improve, 🧪 Experiment

#481 [BE] 0초에서 걸리는 시간 줄이기
  chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/AnswerData.java
  chatty-be/src/main/java/com/chatty/chatty/game/domain/ScoreData.java
  chatty-be/src/main/java/com/chatty/chatty/game/repository/AnswerRepository.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
Labels: 🔨 Refactor

#485 [ML] 방생성 동시 요청 시 jdk 에러 발생
  model/app/app.py
  model/app/data/keyword.py
  model/app/data/preprocessor.py
Labels: 🐞 BugFix

#483 [FE] 코드로 입장하기 구현
  chatty-fe/public/images/bot_not_ready.svg
  chatty-fe/public/images/bot_ready.svg
  chatty-fe/public/images/log-in.svg
  chatty-fe/public/images/share.svg
  chatty-fe/src/app/(game)/create-room/_components/FileUploadBox.tsx
  chatty-fe/src/app/(game)/main-lobby/_components/CodeInput/CodeInput.tsx
  chatty-fe/src/app/(game)/main-lobby/page.css.ts
  chatty-fe/src/app/(game)/main-lobby/page.tsx
  chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizInfoCard/QuizInfoCard.css.ts
  chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizInfoCard/QuizInfoCard.tsx
  chatty-fe/src/app/(game)/waiting-room/[id]/_components/ReadyButton/ReadyButton.css.ts
  chatty-fe/src/app/(game)/waiting-room/[id]/_components/ReadyButton/ReadyButton.tsx
  chatty-fe/src/app/(game)/waiting-room/[id]/_components/UserCard/UserCard.css.ts
  chatty-fe/src/app/(game)/waiting-room/[id]/_components/UserCard/UserCard.tsx
  chatty-fe/src/app/(game)/waiting-room/[id]/_components/UserList/UserList.tsx
  chatty-fe/src/app/(game)/waiting-room/[id]/page.css.ts
  chatty-fe/src/app/(game)/waiting-room/[id]/page.tsx
  chatty-fe/src/app/_api/quiz.ts
  chatty-fe/src/app/_components/GradButton.css.ts
  chatty-fe/src/app/_components/Modal/Modal.css.ts
  chatty-fe/src/app/_components/Modal/Modal.tsx
  chatty-fe/src/app/_components/TextInputField.tsx
  chatty-fe/src/app/_types/QuizInfoType.ts
Labels: ✨ Feature, 🎨 Html&css

#492 [ML] max tokens, max pages 예외 추가
  model/app/app.py
  model/app/data/preprocessor.py
  model/app/data/settings.py
  model/app/model/chain.py
  model/app/model/prompt.py
  model/app/utils/exception.py
Labels: 🔨 Refactor, ⚡ Improve

#497 [BE] :sparkles: Feat: 데이터 서버 예외 status에 따른 백엔드 서버 예외 추가
  chatty-be/src/main/java/com/chatty/chatty/game/exception/ModelExceptionType.java
  chatty-be/src/main/java/com/chatty/chatty/game/service/model/ModelService.java
Labels: ⚡ Improve

#500 [ML] Fix: No features in text.
  model/app/data/keyword.py
  model/app/data/preprocessor.py
  model/app/data/settings.py
Labels: 🐞 BugFix

#501 [ML] Fix: 예외 발생하면 id생성하지 않도록 수정
  model/app/app.py
  model/app/data/keyword.py
Labels: 🐞 BugFix

#519 [FE] 새로고침 시 퀴즈 진행 / 마지막 퀴즈 알림
  chatty-fe/src/app/(game)/quiz-room/[id]/page.tsx
  chatty-fe/src/app/_api/quiz.ts
Labels: 🐞 BugFix, ✨ Feature

#520 [ML] 검색된 문서들과 요약 간의 유사도 검사
  model/app/app.py
  model/app/data/generator.py
  model/app/data/settings.py
  model/app/model/chain.py
Labels: ⚡ Improve

#526 [ML] konlpy 객체 미리 생성 및 재사용을 위한 객체풀 생성
  model/app/app.py
  model/app/data/keyword.py
  model/app/data/preprocessor.py
  model/app/data/tokenizer.py
Labels: ⚡ Improve

#531 [BE] 퀴즈방 생성 이후 10분간 status 가 ready인 방 정리
  chatty-be/src/main/java/com/chatty/chatty/ChattyApplication.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/repository/QuizRoomRepository.java
  chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomScheduler.java
Labels: ⚡ Improve

#537 [FE] :bug: Fix: 채팅에서 chatType 삭제
  chatty-fe/src/app/(game)/waiting-room/[id]/_components/ChatInput/ChatInput.tsx
  chatty-fe/src/app/(game)/waiting-room/[id]/page.tsx
  chatty-fe/src/app/_types/ChatType.ts
  chatty-fe/src/app/_types/WaitingStatus.ts
Labels: 🐞 BugFix
